name: Deploy Frontend to S3 (Test / Prod)

on:
  push:
    branches:
      - test
      - prod
    paths:
      - 'front-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set environment-specific bucket
        run: |
          if [[ "${GITHUB_REF##*/}" == "prod" ]]; then
            echo "S3_BUCKET=${{ secrets.PROD_S3_BUCKET }}" >> $GITHUB_ENV
          else
            echo "S3_BUCKET=${{ secrets.TEST_S3_BUCKET }}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app (Vite)
        run: npm run build
        working-directory: frontend

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "frontend/dist"

      - name: Invalidate CloudFront cache
        run: |
          if [[ "${GITHUB_REF##*/}" == "prod" ]]; then
            DIST_ID=${{ secrets.PROD_CLOUDFRONT_DIST_ID }}
          else
            DIST_ID=${{ secrets.TEST_CLOUDFRONT_DIST_ID }}
          fi

          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
